### PR TITLE
Refactor Hyprland.sh 

### PR DESCRIPTION
**Pull request by brrock**
# Refactor Hyprland.sh 

## Description
This checks if the OS is a Ubuntu or Debain by reading the OS release file and then install hyprland and a dependence using the way the project normally uses, if the OS it is Ubuntu and same for Ubuntu like distros, the script  enables the universe repos required by hyprland and runs sudo apt update. 
## Type of change

Please put an `x` in the boxes that apply:

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [x] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [x] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/JaKooLit/Debian-Hyprland/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/JaKooLit/Debian-Hyprland/blob/main/CONTRIBUTING.md#git-commit-messages).
- [x] My change requires a change to the documentation.
- [x] I want to add something in Debian-Hyprland wiki.
- [x] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by JaKooLit** [comment]
its not good to read OS release else wont be used to distros which are based to either ubuntu or debian

atleast thats what I enountered.. thats why I didnt integrate that function and I have to separate the repo

**Comment by JaKooLit** [comment]
But anyway thanks

I think you accidentally uploades install-logs?

**Comment by brrock** [comment]
Oh sorry I was testing forgot to remove

**Comment by brrock** [comment]
Just updating now

**Comment by brrock** [comment]
Instead of the OS name would the OS ID work

**Comment by JaKooLit** [comment]
> Instead of the OS name would the OS ID work

not sure

if I remember it correctly, Ive even got a message that he tested to another distro, which I didnt even know it exist.

thats why it is safer to not read any from OS releases..

they just need to figure out either based on ubuntu or debian

**Comment by brrock** [comment]
I'm testing on Zorin OS

**Comment by brrock** [comment]
sorry the script is fine I just miss wrote the description sry

**Comment by brrock** [comment]
@JaKooLit

**Comment by brrock** [comment]
Some minor bug fixes

**Comment by brrock** [comment]
@JaKooLit

**Comment by JaKooLit** [comment]
pls, DO NOT keep pinging me....

I already mentioned that I am busy and only at the end of this month that I will be free.....

**Comment by JaKooLit** [comment]
hey...

Managed to review this..

However, wont be merging... as there are lots of adjustments.....

I started already the process..

You will see the "changes" I am making

**Pull request closed without merging**
